replicaCount: 1

nameOverride: ""
fullnameOverride: ""

image:
  repository: mcr.microsoft.com/oss/bitnami/redis
  pullPolicy: IfNotPresent #Always
  tag: "" #image tag should be set in Chart.yaml - but where it's a strange tag, just override here

service:
  type: ClusterIP
  port: 6379

serviceAccount:
  create: false
  annotations: {}
  name: "" #Leave empty and it'll default to the name of the app, thanks to the _helpers.tpl

podSecurityContext: {}
  # fsGroup: 2000